#t is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/launched.yml

ansible_ssh_port: 5985
ansible_connection: winrm
ansible_ssh_user: Administrator
ansible_ssh_pass: NZFW6!2!BpT

